# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7020a89b6b3ca8ca9490b4df30d8dbf41e9760e46c77abe50bfe195abb02e7fb3a5ff6d42b6cd43e772718b83516a5f3b53c7c793327f2caef8dafd38a7a1294
  encryption_key: 'this is a really! long encryption key!!! we like you'

test:
  secret_key_base: 7ce28ae9f7125cec06a4fe21bdb6b5d36429880ec9dec1f5b234dfda71233c08b4454923ec57bcdb857e6e1347ea45b05cdbf6b35928b5e4ea591df4a0fb9c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
